project_id = "abcrgpmwoqsfwtmliqwo"

[functions.parse-resume]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.chat-with-profile]
verify_jwt = false

[functions.enhance-project]
verify_jwt = false
