// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '[PASTE YOUR SUPABASE PROJECT URL HERE]';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '[PASTE YOUR ANON PUBLIC KEY HERE]';

if (!import.meta.env.VITE_SUPABASE_URL) {
  console.error('Supabase initialization failed: VITE_SUPABASE_URL is undefined.');
}

export const supabase = import.meta.env.VITE_SUPABASE_URL
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  })
  : null as any;