// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://fjmcjsffeycwyigicflfk.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFiY3JncG13b3FzZnd0bWxpcXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2OTUyNTcsImV4cCI6MjA4NTI3MTI1N30.GhQ9vE3KkA73nCXATFQtQCQIVdowXpK6utCWoG-4T-Y';

// Even if VITE_SUPABASE_URL is undefined in env, we now have a hardcoded fallback.
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});